- name: variables
  hosts: localhost
  vars: # variable declaration
    course: "Terraform"
    Trainer: "sivakumar"
    Duration: "15hrs"
  tasks: 
  - name: print override information
    vars: # Task level variables
      course: "Terraform"
    ansible.bultin.debug:
      msg: "Hi, I am learning {{course}} from Trainer {{Trainer}}, Duration is {{Duration}}"

  - name: print information
    ansible.builtin.debug:
     msg: "Hi, I am learning {{course}} from Trainer {{Trainer}}, Duration is {{Duration}}"