- name: variables from files
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}. Timings are: {{timings}}"
  
