- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "07:15AM IST"
      Course: "DevOps with AWS"
      Trainer: "sivakumar"
      Duration: "120hrs"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}. 
      Timings are: {{timings}}"