- name: defaulit value
  hosts: localhost
  tasks: 
  - name: print default value
    ansible.builtin.debug:
     msg: "Hello {{course | default('Ansible') }}"

- name:  upper case
  hosts: localhost
  vars:
   greeting: "Hello, Good Morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
     msg: "{{greeting | upper }}"

- name:  lower case
  hosts: localhost
  vars:
   greeting: "Hello, Good Morning"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
     msg: "{{greeting | lower }}"

- name: remove duplites
  hosts: localhost
  vars:
   numbers: [1, 2, 3, 3, 4, 4, 5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
     msg: "{{numbers | unique }}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [25, 35, 67, 89]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: " min age: {{ ages | min }}, max age: {{ ages | max }}"